apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-go
  labels:
    app: learn-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learn-go
  template:
    metadata:
      labels:
        app: learn-go
    spec:
      containers:
      - name: learn-go
        image: learn-go
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: learn-go-service
  labels:  # 添加的标签
    app: learn-go
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32341
  selector:
    app: learn-go

